# -*- coding: utf-8 -*-
"""discord_bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GiiQ-J1_9ZjaXvnHBdclf6eoAdbayFpV
"""

!pip install nest_asyncio 
!pip install discord

import nest_asyncio 
import discord

nest_asyncio.apply()
client = discord.Client(intents=discord.Intents.default())
TOKEN = "MTEwMTg3NzQxOTU0NTIxNDk5Ng.GWuLGv.ZhSjoVy8LJfiN-gzcNiaKz54IFwSa-bHDsaNM4"

@client.event
async def on_ready():
	print("Logged in as")
	print(client.user.name)
	print(client.user.id)
	print("-" * 10)
	print()

@client.event
async def on_message(message):
	print("recieved")
	if message.content.startswith("test"):
		print("recieved")
		await message.channel.send("test")

client.run(TOKEN)